///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GlobalParams
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("a87199f3-751e-4b83-abb6-9bd9bf67a77c", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GlobalParamsRepository repository.
        /// </summary>
        public static GlobalParamsRepository repo = GlobalParamsRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            OpenEdgewords();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AutomatedToolsTestSite.SomeUlTag.BasicHTML' at 23;8.", repo.AutomatedToolsTestSite.SomeUlTag.BasicHTMLInfo, new RecordItemIndex(1));
            repo.AutomatedToolsTestSite.SomeUlTag.BasicHTML.Click("23;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AutomatedToolsTestSite.SomeUlTag.Forms' at 26;9.", repo.AutomatedToolsTestSite.SomeUlTag.FormsInfo, new RecordItemIndex(2));
            repo.AutomatedToolsTestSite.SomeUlTag.Forms.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AutomatedToolsTestSite.SomeUlTag.DynamicContent' at 33;7.", repo.AutomatedToolsTestSite.SomeUlTag.DynamicContentInfo, new RecordItemIndex(3));
            repo.AutomatedToolsTestSite.SomeUlTag.DynamicContent.Click("33;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AutomatedToolsTestSite.SomeUlTag.CSSXPath' at 37;10.", repo.AutomatedToolsTestSite.SomeUlTag.CSSXPathInfo, new RecordItemIndex(4));
            repo.AutomatedToolsTestSite.SomeUlTag.CSSXPath.Click("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AutomatedToolsTestSite.SomeUlTag.Home' at 31;12.", repo.AutomatedToolsTestSite.SomeUlTag.HomeInfo, new RecordItemIndex(5));
            repo.AutomatedToolsTestSite.SomeUlTag.Home.Click("31;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'AutomatedToolsTestSite'.", repo.AutomatedToolsTestSite.SelfInfo, new RecordItemIndex(6));
            Host.Current.CloseApplication(repo.AutomatedToolsTestSite.Self, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
